### ISSUE TITLE
cmd+w doesn't close windows on macos

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#10]
The esc key seems to work, as you would expect on (maybe) windows but on mac the standard cmd+w hotkey doesn't close the windows. This should work for the about, settings, and evidence manager dialogs. We should check to see if there is something that we missed/need to do before just setting up a shortcut key.

**Comment by JoelAtDeluxe** [comment]
Note: Also does not work on linux/gnome.

**Comment by JoelAtDeluxe** [comment]
Addressed in PR #13
