### ISSUE TITLE
Windows client

### ISSUE THREAD

**Issue by securesean** [ashirt-ops/ashirt#111]

**Comment by jrozner** [comment]
We have an existing issue for this already #43. We're hoping that we'll be able to do this with the 1.2.0 release that we have planned but have run into a few issues that we haven't solved with the Qt6 port. We're hoping to have this done sometime in Q2 along with an installer. It's not clear yet how much code will need to change to support Windows but we do need to identify a screenshot solution for it as the built in tools do not provide the necessary functionality.

Going to close this as a duplicate.
