### ISSUE TITLE
Crash on quit

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#148]
**OS version** (`uname -a` if on a Unix-like system. For windows run `winver` and copy the text starting "Version "): win 11 (though likely others)

**QT version** *if dynamically linking* (`qtdiag |head -n 3`): qt 6.3.0

**Description of the problem including expected versus actual behavior**: Reproducible crash on exit from ashirt. Not sure of the exact conditions for replication but I believe it has something to do with in flight http requests attempting to contact the server to retrieve the operations when opening the context menu from the tray icon and it not being complete.

**Steps to reproduce**:

 1. Run ashirt with a server configured but not running
 2. Right click on tray icon
 3. Select quit

**Provide logs (if relevant)**:
```
0:000> k
 # Child-SP          RetAddr               Call Site
00 000000ab`1d3df6c0 00007ff6`4fbf87c5     ashirt+0x1c064
01 000000ab`1d3df6f0 00007fff`9d95bea0     ashirt+0x687c5
02 000000ab`1d3df720 00007fff`9d95bdb7     ucrtbase!<lambda_f03950bc5685219e0bcd2087efbe011e>::operator()+0xb0
03 000000ab`1d3df770 00007fff`9d95bd6d     ucrtbase!__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda_f03950bc5685219e0bcd2087efbe011e> &,<lambda_3883c3dff614d5e0c5f61bb1ac94921c> >+0x3b
04 000000ab`1d3df7a0 00007fff`9d95a17a     ucrtbase!execute_onexit_table+0x3d
05 000000ab`1d3df7e0 00007fff`9d95a10f     ucrtbase!<lambda_ad52fe89635f51ec3b38e9c3ac6dac81>::operator()+0x42
06 000000ab`1d3df820 00007fff`9d95a0af     ucrtbase!__crt_seh_guarded_call<void>::operator()<<lambda_123965863b7b46a3332720573f9ce793>,<lambda_ad52fe89635f51ec3b38e9c3ac6dac81> &,<lambda_8d528b66de6ae1e796d7f5e3101fca72> >+0x3b
07 000000ab`1d3df850 00007ff6`4fbd7c14     ucrtbase!common_exit+0x67
08 000000ab`1d3df8b0 00007fff`9efd54e0     ashirt+0x47c14
09 000000ab`1d3df8f0 00007fff`9fbc485b     KERNEL32!BaseThreadInitThunk+0x10
0a 000000ab`1d3df920 00000000`00000000     ntdll!RtlUserThreadStart+0x2b
```

**Comment by crizzitello** [comment]
Just Tested MacOs and Linux Happens only on windows (also 10)
