### ISSUE TITLE
Out of Date build directions in Readme_Developer.md

### ISSUE THREAD

**Issue by shitwolfymakes** [ashirt-ops/ashirt#243]
**OS version**: Linux ubuntu-desktop-1 6.2.0-35-generic (Ubuntu 22.04 LTS)

**Description of the problem including expected versus actual behavior**:
Tried to build this following the instructions in `Readme_Developer.md`, an ran into a failure. 
1) Following the guide, I tried to build using Qt 5.15.2. The CMake configuration step fails because the CMakeLists.txt actually requires Qt 6.5+.
2) The guide fails to include an install command for Ubuntu/Debian systems, `apt install sqlite3` worked for me.
3) Building a configured project fails with the error `xcb/xcb_keysyms.h: No such file or directory` at `uglobalhotkeys.h:9` and `hotkeymap.h:129`. A note to install the XCB library should be included alongside SQLite3. The working command for that is: `apt install libxcb-keysyms1-dev` for Ubuntu/Debian. The installation command will vary for yum and pacman-based systems.
4) Not a build error, but the document refers to the qmake `ashirt.pro` build file instead of the new `CMakeLists.txt` file.

**Steps to reproduce**: Try to build on an Ubuntu 22.04 system following the guide.

**Comment by jkennedyvz** [comment]
Thanks for pointing this out. Current build "documentation" is the github actions workflow. I can take some time this quarter to clean up the dev instructions to reflect this year's changes.
