### ISSUE TITLE
Migrate file paths to QDir

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#32]
This is going to be needed if/when we eventually support Windows due to the path separator being different. We might as well do this now and have it in place so it's there when we need it. Doing do requires that we bump the C++ standard up to C++17 but I don't anticipate that being an issue. We should be able to build the paths with std::filesystem::path and convert it into a String/c_str which can be fed into the constructors that currently use the path.

**Comment by jrozner** [comment]
It looks like Qt has it's own QDir class that handles correctly using directory separators depending on the operating system. Let's use that instead of std::filesystem:path instead to make this easier to compile.

**Comment by JoelAtDeluxe** [comment]
Yeah, I almost responded with something similar, but figured std::filepath might be safer/more universal
