### ISSUE TITLE
Make shortcut selector read user input

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#4]
Currently to set global shortcuts requires typing the values (eg. Alt+4) into the text box in the settings. This is error prone and not always clear what the correct thing to type should be. Instead we should allow that text box to read keyboard input and automatically fill in the value based on the key codes read. This will also serve as canonicalization to ensure that the values are the same.

**Comment by JoelAtDeluxe** [comment]
Addressed in PR #20
