### ISSUE TITLE
Multi-display doesn't work

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#46]
**OS version** (`uname -a` if on a Unix-like system. For windows run `winver` and copy the text starting "Version "):
Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

**QT version** *if dynamically linking* (`qtdiag |head -n 3`):
Qt 5.15.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by Clang 11.0.3 (clang-1103.0.32.62) (Apple)) on "cocoa" OS: macOS 10.15 [darwin version 19.6.0]

**Description of the problem including expected versus actual behavior**:
When clicking on the system tray icon on the primary display (in a multidisplay environment) nothing happens. It works fine on the non-primary display. This might just be a bug in Qt on macos and not an application bug. It's probably just worth asking in #qt on freenode and seeing if this is a known issue and/or if there are workarounds/something we missed. I haven't see anything that directly references this issue but I haven't done a ton of googling or know exactly what we'd search for to find meaningful results.

**Steps to reproduce**:

 1. Start application on a system with two displays
 2. Click traybar icon on primary display

**Comment by JoelAtDeluxe** [comment]
I can't seem to reproduce this on my macbook. Are you using a particular release or more than 2 monitors (counting the macbook display itself)?  Or does this only happen if you add a display after the application is started?

**Comment by jrozner** [comment]
Have seen it occur with two monitors (including macbook display) when the second display is not setup to mirror. In mirror mode is definitely works. Running a pretty standard macos 10.15.6 with no weird extensions or software installed that may effect the layout or anything. This behavior has been reported by others on the team as well. Have verified that it occurs if both monitors are connected and setup when the application starts or if the second monitor is attached after the application starts.

**Comment by jrozner** [comment]
Confirmed that this appears to either be related to using Qt 5.15 or the version that is distributed by homebrew. Testing a build from @JoelAtDeluxe using the officially distributed Qt 5.14 this issue went away. Going to install the official 5.15 distribution and check if the issue still occurs. If so, will report the bug upstream. If not, we can switch over to the official distribution for now and file a bug with homebrew.

**Comment by jrozner** [comment]
Tested this again on qt 5.15.1 from homebrew on macos and it still seems broken. This appears to maybe be an issue with the specific distribution from homebrew. Going to check if we can easily build with official versions from Qt in github actions.

**Comment by jrozner** [comment]
After more testing we've finally identified the conditions that cause it to break. It's been replicated on official Qt releases as well. This seems to explicitly only happen in a multi-monitor environment when the primary monitor is arranged below the secondary monitor. Searching the bug tracker for Qt doesn't show any known issues, working to figure out how to get this reported and figure out how to get it fixed.

**Comment by jrozner** [comment]
The bug has been reported upstream to Qt https://bugreports.qt.io/browse/QTBUG-87177. Waiting to see what they say.

**Comment by jrozner** [comment]
Need to check whether this is still present in Qt 6. If not, we can close this as we no longer support Qt 5.

**Comment by jrozner** [comment]
Confirmed this is fixed on Qt 6.3 using the most recent continuous build. Since we don't support Qt 5 anymore, we can close this.
