### ISSUE TITLE
Local operation deletion

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#49]
Currently when cleaning up an operation a user must go through and remove all of the evidence one by one and remove them (file and database entry). This is pretty tedious and leaves behind the directory in the evidence repo once everything is gone. #48 will help make this better but we should probably create some one click (plus a confirmation that you actually want to do it) way to delete all the evidence for an operation (files and rows) and the directory in the evidence repository.

**Comment by JoelAtDeluxe** [comment]
With regards to deleting the directory, I think the proper thing to do will be to remove all of the files we know about, then check the size of the directory. if it's empty, then delete. Or maybe there's a command I can blindly execute (ala `rmdir`) that will do that check for me.

**Comment by jrozner** [comment]
Ya, I 100% agree that that's the correct solution. I think we generally want to make sure if we're deleting files we also delete the database entries and we don't delete the directory until all evidence is gone. We probably do want a simple way to just do all that at once though.
