### ISSUE TITLE
Fix image display/layout in the evidence viewer

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#5]
Currently the layout causes images to not be displayed within the evidence viewer. This seems to be because the size of the window is just too small on 13" macs. This whole UI should change somewhat with the new tagging system (#9) and some layout changes for buttons and action handling (#6, #7, #8).
<img width="801" alt="Screen Shot 2020-06-30 at 10 28 32 AM" src="https://user-images.githubusercontent.com/26415/86157775-b914fd80-babc-11ea-965e-03c46a71b12b.png">
<img width="802" alt="Screen Shot 2020-06-30 at 10 29 30 AM" src="https://user-images.githubusercontent.com/26415/86157789-bd411b00-babc-11ea-8acc-5e34d816b320.png">

**Comment by JoelAtDeluxe** [comment]
While we will reclaim some space from the mentioned PRs, I think we may need to do something additional. The prior version (leaving description on the same row as the preview) works well for images, not as well for codeblocks. The current incarnation has the opposite issue. 

A couple of possibilities:
1. Have two views: one for codeblocks, one for images. This is somewhat complicated and messy, but may be worthwhile to have a nice view for each.
2. Have images (and I suppose codeblocks) have a way to view their content in large form, via a new window (similar to how the front end does things)
3. Move the preview/description/tags area to the right, in a new column.

We'll probably want to address this after the other issues mentioned above are addressed.

**Comment by jrozner** [comment]
Ya, I agree. I think we should wait on this until we get the new tag system implemented and some of the other changes done to this screen so we have a better idea of the amount of space needed. I think 2 and 3 are going to be the better options and maybe we can think through some other options if neither work out well or there is something better.

**Comment by JoelAtDeluxe** [comment]
First attempt at a better design in PR #29
