### ISSUE TITLE
Move submit/resubmit functionality into a context menu

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#6]
Currently the evidence manager has a submit button on the button the dialog. Move this functionality into a "right-click" context menu on the evidence line in the table above.
<img width="801" alt="Screen Shot 2020-06-30 at 10 28 32 AM" src="https://user-images.githubusercontent.com/26415/86158107-2c1e7400-babd-11ea-9b1a-c867954c3d5c.png">

**Comment by JoelAtDeluxe** [comment]
Addressed in PR #16
