### ISSUE TITLE
Add ability to create a new operation

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#65]
Currently creating a new operation requires going into the ashirt web application. Provide the ability to create a new one directly from the ashirt application. This will depend on an endpoint being getting added into the api server to allow for this functionality. The design is currently such that the api server has limited read/edit access so that it can be permitted to live in a more permissive network space (eg. the internet) while the web interface can live somewhere more restrictive (corp). There isn't currently any plan to switch from this but we may need to evaluate that depending on if new management functionality is desired to be added to ashirt (eg. adding users, editing/delete tags, etc.)

**Comment by JoelAtDeluxe** [comment]
Fixed in PR #66
