### ISSUE TITLE
Move delete into context-menu

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#7]
Currently the delete option for specific evidence is performed by a button at the bottom right of the evidence viewer. Instead move this functionality into a "right-click" context-menu.
<img width="801" alt="Screen Shot 2020-06-30 at 10 28 32 AM" src="https://user-images.githubusercontent.com/26415/86158259-62f48a00-babd-11ea-8d7e-7c3e5f26dd42.png">

**Comment by JoelAtDeluxe** [comment]
Addressed in PR #16
