### ISSUE TITLE
Remove close button

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#8]
Remove the close button from the bottom right of the evidence viewer. Normal hotkeys and windows buttons should be sufficient.
<img width="801" alt="Screen Shot 2020-06-30 at 10 28 32 AM" src="https://user-images.githubusercontent.com/26415/86158485-afd86080-babd-11ea-9684-eeb6b6ed1691.png">

**Comment by JoelAtDeluxe** [comment]
Addressed in PR #12
