### ISSUE TITLE
Make it possible to edit the description for non-submitted evidence

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#89]
For evidence that hasn't yet been submitted it should be possible to edit the description and tags.

**Comment by JoelAtDeluxe** [comment]
I created a PR to handle this scenario. The way it's intended to work is as follows:
Within the evidence manager, a user can click on a piece of evidence.
* If it's submitted, then there's no change (technically, there's now a disabled edit button, with the tool tip that indicates you can only edit unsubmitted evidence)
* If it's unsubmitted, then the user can click the edit button, and the description/tags fields become editable, as you would get when you first create the evidence. From here, you can click cancel, which should restore the state of the evidence, or  save, which will update the evidence locally, but still not submit the evidence.
Edit only works when exactly one item is selected. Any more or less and the button is grayed out with messaging indicating to select one item.
