### ISSUE TITLE
Replace current tagging UI

### ISSUE THREAD

**Issue by jrozner** [ashirt-ops/ashirt#9]
The current tagging UI takes up a lot of space and isn't as simple as it is on the web interface. We want to build something that more closely resembles what we have in the web ui.

## Requirements
- Colors of tags match the colors in the web UI
- Ability to type tags in a bar and have them autocomplete if exist
- Creation of new tags upon hitting return if the tag does not already exist for the operation
- Ability to pin/remember tags to have them automatically show up on future evidence until unpinned. This can either use explicit pinning or just remember the last tags used for an initial version, whichever is easier

**Comment by JoelAtDeluxe** [comment]
Addressed in PR #23
